---
driver:
  name: ec2
  region: us-east-2
  subnet_id: subnet-0f47f35ab0d9537d3
  instance_type: t3.micro


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[chef-workshop-lab1::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
